Twitter bot
webaverse/ethereum-bot pull request #11
Opened 2021-01-29 20:18 UTC by shawticus

This covers the rest of the functionality for the Twitter bot.

The only main functionality not handled here is trading, since we will need to resolve what that interaction would actually look like. 

Gif previews are also not currently supported.

Everything else should work the same as the Discord bot, although some of the text has been formatted to be a bit friendlier and more informative.

Also, currently "help" links to the discord bot documentation, this will need to be updated.

You will need to add production keys to test, into the config.json.

These features *should* work but need testing by someone with production credentials
play
unsell
buy
store

2021-01-29 22:54 UTC, avaer commented
Do we need `tmp`? Can't this all be done in memory?

2021-01-29 23:04 UTC, shawticus commented
I could work on it but piping the output of one request into the input of
another is not something I've ever done, and I was having issues it with so
I figured I'd cache the jpg for a second before uploading and deleting it,
since FS makes sense to me :) but yeah, definitely better to do in memory
if possible.

On Fri, Jan 29, 2021 at 2:55 PM Avaer Kazmer <notifications@github.com>
wrote:

> Do we need tmp? Can't this all be done in memory?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/webaverse/ethereum-bot/pull/11#issuecomment-770092963>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEOFEMA3FC7Z6FI7P54AIJ3S4M4EXANCNFSM4WZOPCYQ>
> .
>

2021-01-29 23:11 UTC, chrislatorres commented
Could it be kept as a file blob (https://developer.mozilla.org/en-US/docs/Web/API/Blob) until it is minted?

2021-01-29 23:15 UTC, avaer commented
Could it be kept as a file blob
> No because this is node which does not have official `Blob`.

This code can be copied instead: https://github.com/webaverse/ethereum-bot/blob/27c4782f81735de92c0fd5fe9923dd793ad65008/discordbot.js#L2231

The traditional way is to flow the request/response.

2021-01-30 07:20 UTC, avaer commented on twitterBot.js
> +    downloadMedia(newUrl, filePath, function () {
This could be async.

2021-01-30 07:21 UTC, avaer commented on twitterBot.js
> +      finishMinting(id, twitterUserId, manualUrl, quantity, event, messageType, filePath)
`await`?

2021-01-30 07:49 UTC, avaer commented
This there a way to do this without `ngrok`?

2021-01-30 07:53 UTC, avaer commented on twitterBot.js
> +    downloadMedia(newUrl, filePath, function () {
Could be `await`.

2021-01-30 07:53 UTC, avaer commented on twitterBot.js
> +      finishUpdating(id, twitterUserId, manualUrl, nftId, event, messageType, filePath)
`await`

2021-01-30 07:53 UTC, avaer commented on twitterBot.js
> +    finishMinting(id, twitterUserId, manualUrl, quantity, event, messageType)
`await`

2021-01-30 07:54 UTC, avaer commented on twitterBot.js
> +    finishUpdating(id, twitterUserId, manualUrl, nftId, event, messageType)
`await`

2021-01-30 07:58 UTC, avaer commented
This overall looks good, just the questions of:

- avoiding disk
- necessity of `ngrok` (less important, would need to set up our own keys for deploy)

2021-01-30 08:01 UTC, avaer commented on twitterBot.js
> +  twitterBearerToken,
`twitterBearerToken` looks unused.

2021-01-30 08:02 UTC, avaer requested changes
Looks good overall, just some cleanups and avoiding disk.

2021-01-31 02:09 UTC, avaer commented
Should make sure this isn't consuming the stream: https://github.com/webaverse/ethereum-bot/pull/11/files#diff-c6a1938c899065d78caa9fdf781aeae99f6262dddb9a7c77fd8d3536877ccaf6R896

Can probably just use `http[s].request`.

2021-02-01 01:57 UTC, avaer commented on constants.js
> +exports.twitterUsersTableName = 'users';
Not used anymore.

2021-02-01 02:02 UTC, avaer commented
I'm gonna clean this up so we can ship it.

2021-02-01 02:34 UTC, avaer commented on discordbot.js
> +                                                    extName = extName === "jpeg" ? "jpg" : extName
It might be best to do this on the frontend.

2021-02-01 02:53 UTC, avaer approved these changes

2021-02-01 03:07 UTC, merged